### PR TITLE
Fix access of zoom value 

### PR DESCRIPTION
**Pull request by painpita**
@HisashiHasebe 
@jassiG 
We can access zoom value like this.

### CODE REVIEW

**Comment by HisashiHasebe** [comment]
@painpita @jassiG 
The API request is sent just by placing a pin on Google Maps. Can it be changed to work the same way as in Nuxt2 (only sending the API request when clicking "Save")?

`http://localhost:3000/` : Nuxt2
`https://hasebetest2.g.kuroco-front.app/` : Nuxt3
https://diverta.gyazo.com/cbec090c7cf405513226e8541a7b768b

**Comment by painpita** [comment]
@HisashiHasebe 
Ah of course, ill modify the behavior, sorry for the oversight

**Comment by jassiG** [comment]
https://github.com/diverta/front_kuroco_document_site/issues/1172

**Comment by HisashiHasebe** [comment]
@painpita 
Thank you! I confirmed work well.

I will update documents.

**Pull request merged**
